#!/usr/bin/env python
"""fbs>1 batched-rollout prototype + numerical validation for BAGEL (cfg=1 T2I).

BAGEL runs navit bs=1: each GRPO sibling is denoised in its own _forward_flow
call. The vendored packing (prepare_vae_latent loops over image_sizes; attention
is flash_attn_varlen with per-sample cu_seqlens) ALREADY supports multiple
samples in one packed forward -- the bs=1 limit lives in UniRL's adapter.

This script prototypes the batched forward in the ADAPTER layer (no vendored
edit) and validates it numerically:

  Claim 1 (forward correctness): for K samples sharing a prompt, the batched
    _forward_flow velocity for each sample matches the bs=1 velocity within bf16
    tolerance -> the varlen attention isolates samples (block-diagonal), so
    batching changes only GEMM shapes (bf16 rounding), not the math.

  Claim 2 (ratio=1 preserved): a trajectory generated by the batched path, when
    replayed at bs=1 (the train micro-geometry), gives a deterministic log-prob
    (two replays bit-identical) -> with old_logp_source=replay the PPO ratio is
    exactly 1 on update 1, regardless of how the trajectory was sampled. This is
    the SD3 pattern (sample batched, anchor pi_old via bs=1 replay).

Run (single GPU, no FSDP, occupier suppressed):
  BAGEL_PATH=/data/models/BAGEL-7B-MoT \
  CUDA_VISIBLE_DEVICES=0 python scripts/profiling/validate_fbs_batched.py
"""

from __future__ import annotations

import os

import torch

from unirl.models.bagel.config import BagelPipelineConfig
from unirl.models.bagel.diffusion import BagelDiffusionParams
from unirl.models.bagel.pipeline import BagelPipeline
from unirl.models.bagel.rl_ops import _to_device
from unirl.models.bagel.vendor.modeling.bagel.qwen2_navit import NaiveCache
from unirl.sde.runtime import get_sigma_schedule

K = int(os.environ.get("FBS_K", "4"))
PROMPT = os.environ.get("FBS_PROMPT", "a watercolor painting of a fox in a snowy forest")


def _concat_caches(caches):
    """Concatenate K NaiveCache prompt KVs along the sequence dim (per layer).

    Empty contexts (e.g. the T2I cfg_text branch, which is the pre-text snapshot
    with kv_len=0) carry None per-layer tensors; an all-None layer stays None
    (matches forward_inference's ``past_key_values.key_cache[l] is None`` path).
    """
    out = NaiveCache(caches[0].num_layers)
    for layer in range(caches[0].num_layers):
        keys = [c.key_cache[layer] for c in caches]
        if all(k is None for k in keys):
            out.key_cache[layer] = None
            out.value_cache[layer] = None
        else:
            out.key_cache[layer] = torch.cat(keys, dim=0)
            out.value_cache[layer] = torch.cat([c.value_cache[layer] for c in caches], dim=0)
    return out


def _batched_generation_inputs(stage, gens, cfg_texts, cfg_imgs, image_shape, device):
    """K-sample analog of BagelDiffusionStage._build_generation_inputs.

    prepare_vae_latent / prepare_vae_latent_cfg already loop over image_sizes, so
    passing K kvlens / ropes / shapes yields correctly-offset packed indexes for
    K samples; the only extra work is concatenating the K prompt KV caches.
    """
    bagel = stage.model.model
    kvlens = [int(g["kv_lens"][0]) for g in gens]
    ropes = [g["ropes"][0] for g in gens]
    image_sizes = [image_shape] * len(gens)
    gi = bagel.prepare_vae_latent(
        curr_kvlens=kvlens, curr_rope=ropes, image_sizes=image_sizes, new_token_ids=stage.model.new_token_ids
    )
    gi_ct = bagel.prepare_vae_latent_cfg(
        curr_kvlens=[int(c["kv_lens"][0]) for c in cfg_texts],
        curr_rope=[c["ropes"][0] for c in cfg_texts],
        image_sizes=image_sizes,
    )
    gi_ci = bagel.prepare_vae_latent_cfg(
        curr_kvlens=[int(c["kv_lens"][0]) for c in cfg_imgs],
        curr_rope=[c["ropes"][0] for c in cfg_imgs],
        image_sizes=image_sizes,
    )
    return _to_device(gi, device), _to_device(gi_ct, device), _to_device(gi_ci, device)


def _batched_forward_kwargs(stage, gens, cfg_texts, cfg_imgs, gi, gi_ct, gi_ci, params):
    """K-sample analog of _forward_kwargs: concat the three past KV caches."""
    return dict(
        packed_vae_token_indexes=gi["packed_vae_token_indexes"],
        packed_vae_position_ids=gi["packed_vae_position_ids"],
        packed_text_ids=gi["packed_text_ids"],
        packed_text_indexes=gi["packed_text_indexes"],
        packed_position_ids=gi["packed_position_ids"],
        packed_indexes=gi["packed_indexes"],
        packed_seqlens=gi["packed_seqlens"],
        key_values_lens=gi["key_values_lens"],
        past_key_values=_concat_caches([g["past_key_values"] for g in gens]),
        packed_key_value_indexes=gi["packed_key_value_indexes"],
        cfg_renorm_min=params.cfg_renorm_min,
        cfg_renorm_type=params.cfg_renorm_type,
        cfg_text_packed_position_ids=gi_ct["cfg_packed_position_ids"],
        cfg_text_packed_query_indexes=gi_ct["cfg_packed_query_indexes"],
        cfg_text_key_values_lens=gi_ct["cfg_key_values_lens"],
        cfg_text_past_key_values=_concat_caches([c["past_key_values"] for c in cfg_texts]),
        cfg_text_packed_key_value_indexes=gi_ct["cfg_packed_key_value_indexes"],
        cfg_img_packed_position_ids=gi_ci["cfg_packed_position_ids"],
        cfg_img_packed_query_indexes=gi_ci["cfg_packed_query_indexes"],
        cfg_img_key_values_lens=gi_ci["cfg_key_values_lens"],
        cfg_img_past_key_values=_concat_caches([c["past_key_values"] for c in cfg_imgs]),
        cfg_img_packed_key_value_indexes=gi_ci["cfg_packed_key_value_indexes"],
        cfg_type=params.cfg_type,
    )


def main() -> None:
    torch.manual_seed(0)
    device = torch.device("cuda:0")
    ckpt = os.environ["BAGEL_PATH"]
    print(f"[fbs] loading BAGEL from {ckpt} (K={K}) ...", flush=True)
    cfg = BagelPipelineConfig(pretrained_model_ckpt_path=ckpt, model_precision="bf16", shift=3.0, use_lora=False)
    pipe = BagelPipeline.from_config(cfg)
    stage = pipe.diffusion
    bagel = stage.model.model
    params = BagelDiffusionParams(
        num_inference_steps=14, cfg_text_scale=1.0, cfg_img_scale=1.0, eta=1.0, height=512, width=512
    )
    image_shape = (params.height, params.width)

    # One shared prompt context (T2I, frozen und path).
    gen, cfg_text, cfg_img = pipe._build_contexts(PROMPT)
    seq = (params.height // (bagel.latent_downsample)) * (params.width // (bagel.latent_downsample))
    cdim = bagel.latent_channel * (bagel.latent_patch_size**2)
    print(f"[fbs] per-sample packed latent: seq={seq} C={cdim}; prompt kv_len={int(gen['kv_lens'][0])}", flush=True)

    # K per-sample initial latents (distinct noise, same prompt).
    x_list = [torch.randn(seq, cdim, device=device, dtype=stage.trajectory_dtype) for _ in range(K)]
    t_cur = torch.tensor(1.0, device=device)

    with torch.no_grad(), stage._autocast_ctx(device):
        # --- bs=1 reference: one _forward_flow per sample (current path) ---
        gi, gi_ct, gi_ci = stage._build_generation_inputs(gen, cfg_text, cfg_img, image_shape, device=device)
        fk1 = stage._forward_kwargs(gen, cfg_text, cfg_img, gi, gi_ct, gi_ci, params)
        v_bs1 = [
            stage.step.predict_velocity(
                bagel, x_t=x, t_cur=t_cur, cfg_text_scale=1.0, cfg_img_scale=1.0, forward_kwargs=fk1
            )
            for x in x_list
        ]

        # --- batched: ONE _forward_flow for all K samples ---
        gens, cts, cis = [gen] * K, [cfg_text] * K, [cfg_img] * K
        bgi, bgi_ct, bgi_ci = _batched_generation_inputs(stage, gens, cts, cis, image_shape, device)
        fkB = _batched_forward_kwargs(stage, gens, cts, cis, bgi, bgi_ct, bgi_ci, params)
        x_packed = torch.cat(x_list, dim=0)
        v_packed = stage.step.predict_velocity(
            bagel, x_t=x_packed, t_cur=t_cur, cfg_text_scale=1.0, cfg_img_scale=1.0, forward_kwargs=fkB
        )
        v_batched = list(v_packed.split(seq, dim=0))

    # ---- Claim 1: batched per-sample velocity ~= bs=1 velocity ----
    print("\n[Claim 1] batched _forward_flow velocity vs bs=1 (per sample):", flush=True)
    ok1 = True
    for k in range(K):
        a, b = v_bs1[k].float(), v_batched[k].float()
        max_abs = (a - b).abs().max().item()
        rel = ((a - b).norm() / (a.norm() + 1e-8)).item()
        # bf16 relative tolerance: GEMM batch-shape sensitivity is ~1e-2 relative.
        passed = rel < 2e-2
        ok1 = ok1 and passed
        print(f"  sample {k}: max|dv|={max_abs:.4e}  rel_l2={rel:.4e}  {'OK' if passed else 'FAIL'}", flush=True)
    # Cross-sample isolation: batched sample 0 must NOT equal bs=1 sample 1.
    cross = ((v_batched[0].float() - v_bs1[1].float()).norm() / (v_bs1[1].float().norm() + 1e-8)).item()
    print(f"  cross-check rel_l2(batched[0] vs bs1[1]) = {cross:.4e} (should be O(1), not ~0)", flush=True)

    # ---- Claim 2: bs=1 replay is deterministic -> ratio=1 on update 1 ----
    # Build a short stored trajectory for ONE sample via the existing bs=1 diffuse,
    # then replay it twice; identical log-probs => exp(new-old)=1 exactly.
    print("\n[Claim 2] bs=1 replay determinism (ratio=1 anchor):", flush=True)
    schedule = get_sigma_schedule(params.num_inference_steps, shift=3.0, device=device)
    params_traj = BagelDiffusionParams(
        num_inference_steps=14,
        cfg_text_scale=1.0,
        cfg_img_scale=1.0,
        eta=1.0,
        height=512,
        width=512,
        sde_indices=[0, 3],
    )
    cond = pipe._build_contexts(PROMPT)
    from unirl.models.bagel.conditions import BagelDiffusionConditions

    cond1 = BagelDiffusionConditions.for_sample(
        gen_context=cond[0], cfg_text_context=cond[1], cfg_img_context=cond[2], image_shape=image_shape
    )
    seg = stage.diffuse(cond1, schedule=schedule, params=params_traj, initial_latents=x_list[0])
    rep1 = stage.replay(cond1, segment=seg, params=params_traj)
    rep2 = stage.replay(cond1, segment=seg, params=params_traj)
    lp1, lp2 = rep1.log_probs.float(), rep2.log_probs.float()
    ratio = torch.exp(lp1 - lp2)
    max_ratio_dev = (ratio - 1.0).abs().max().item()
    old = seg.sde_logp.float()
    ratio_vs_rollout = torch.exp(rep1.log_probs.float() - old)
    print(f"  replay#1 vs replay#2 log_probs: max|ratio-1| = {max_ratio_dev:.3e} (expect 0)", flush=True)
    print(
        f"  replay vs stored rollout logp: ratio mean={ratio_vs_rollout.mean().item():.6f} "
        f"max|dev|={(ratio_vs_rollout - 1).abs().max().item():.3e}",
        flush=True,
    )
    ok2 = max_ratio_dev < 1e-6

    print("\n==== RESULT ====", flush=True)
    print(f"  Claim 1 (batched==bs1 velocity, bf16 tol): {'PASS' if ok1 else 'FAIL'}", flush=True)
    print(f"  Claim 2 (bs=1 replay deterministic ratio=1): {'PASS' if ok2 else 'FAIL'}", flush=True)

    # ---- Shipped optimization: context-cache is a PURE speedup (zero behavior change) ----
    # diffuse() is stochastic (SDE steps draw fresh noise, no generator -- by design), so
    # comparing trajectories is meaningless. The cache's only effect is reusing the context
    # build, so the right test is DETERMINISTIC: the cached prompt KV cache must be
    # bit-identical to an independent fresh build, and a velocity forward (no SDE noise) on
    # the cached vs fresh context must match exactly.
    print("\n[cache] context-cache identity (the shipped -11% optimization):", flush=True)
    pipe.clear_context_cache()
    ga, ta, ia = pipe._build_contexts(PROMPT)  # cache OFF: fresh build
    gb, tb, ib = pipe._build_contexts_cached(PROMPT)  # cache ON: build + store
    same_obj = pipe._build_contexts_cached(PROMPT)[0] is gb  # 2nd call = cache hit (same object)
    kv_off, kv_on = ga["past_key_values"], gb["past_key_values"]
    kv_diff = max(
        (kv_off.key_cache[layer].float() - kv_on.key_cache[layer].float()).abs().max().item()
        for layer in range(kv_off.num_layers)
        if kv_off.key_cache[layer] is not None
    )
    noise_c = torch.randn(seq, cdim, device=device, dtype=stage.trajectory_dtype)
    with torch.no_grad(), stage._autocast_ctx(device):
        gi_o, ct_o, ci_o = stage._build_generation_inputs(ga, ta, ia, image_shape, device=device)
        v_off = stage.step.predict_velocity(
            bagel,
            x_t=noise_c,
            t_cur=t_cur,
            cfg_text_scale=1.0,
            cfg_img_scale=1.0,
            forward_kwargs=stage._forward_kwargs(ga, ta, ia, gi_o, ct_o, ci_o, params),
        )
        gi_n, ct_n, ci_n = stage._build_generation_inputs(gb, tb, ib, image_shape, device=device)
        v_on = stage.step.predict_velocity(
            bagel,
            x_t=noise_c,
            t_cur=t_cur,
            cfg_text_scale=1.0,
            cfg_img_scale=1.0,
            forward_kwargs=stage._forward_kwargs(gb, tb, ib, gi_n, ct_n, ci_n, params),
        )
    v_diff = (v_off.float() - v_on.float()).abs().max().item()
    ok_cache = kv_diff == 0.0 and v_diff == 0.0 and same_obj
    print(f"  prompt-KV max|diff| (fresh vs cached) = {kv_diff:.3e}", flush=True)
    print(f"  velocity max|diff| (same x_t, deterministic) = {v_diff:.3e}", flush=True)
    print(f"  cache hit returns same object: {same_obj}", flush=True)
    print(f"  -> PURE speedup, zero behavior change: {'PASS' if ok_cache else 'FAIL'}", flush=True)

    if os.environ.get("FBS_BENCH", "0") != "1":
        print("\n[bench] skipped (set FBS_BENCH=1 to time the fbs>1 speedup)", flush=True)
        return

    # ---- Real measurement: rollout-generate speedup (bs=1 loop vs batched) ----
    print(
        "\n[bench] denoise-loop wall-clock: K bs=1 forwards vs 1 batched forward "
        f"(T={params.num_inference_steps} steps)",
        flush=True,
    )
    import time as _time

    sched = get_sigma_schedule(params.num_inference_steps, shift=3.0, device=device)
    Tn = int(params.num_inference_steps)
    smax = float(sched[1])

    def _bs1_loop(xs):
        gi_, ct_, ci_ = stage._build_generation_inputs(gen, cfg_text, cfg_img, image_shape, device=device)
        fk_ = stage._forward_kwargs(gen, cfg_text, cfg_img, gi_, ct_, ci_, params)
        for x0 in xs:
            x = x0
            for i in range(Tn):
                v = stage.step.predict_velocity(
                    bagel, x_t=x, t_cur=sched[i], cfg_text_scale=1.0, cfg_img_scale=1.0, forward_kwargs=fk_
                )
                prev, _, _ = stage.strategy.denoise(
                    noise_pred=v.unsqueeze(0),
                    sample=x.unsqueeze(0),
                    sigma=sched[i],
                    sigma_next=sched[i + 1],
                    eta=0.0,
                    sigma_max=smax,
                )
                x = prev.squeeze(0).to(stage.trajectory_dtype)

    def _batched_loop(xs):
        gensK, ctsK, cisK = [gen] * len(xs), [cfg_text] * len(xs), [cfg_img] * len(xs)
        bgi_, bct_, bci_ = _batched_generation_inputs(stage, gensK, ctsK, cisK, image_shape, device)
        fk_ = _batched_forward_kwargs(stage, gensK, ctsK, cisK, bgi_, bct_, bci_, params)
        nK = len(xs)
        x = torch.cat(xs, dim=0)
        for i in range(Tn):
            v = stage.step.predict_velocity(
                bagel, x_t=x, t_cur=sched[i], cfg_text_scale=1.0, cfg_img_scale=1.0, forward_kwargs=fk_
            )
            vK, xK = v.view(nK, seq, -1), x.view(nK, seq, -1)
            prev, _, _ = stage.strategy.denoise(
                noise_pred=vK,
                sample=xK,
                sigma=sched[i],
                sigma_next=sched[i + 1],
                eta=0.0,
                sigma_max=smax,
            )
            x = prev.reshape(nK * seq, -1).to(stage.trajectory_dtype)

    print(f"  {'K':>3} | {'bs=1 (s)':>10} | {'batched (s)':>12} | {'speedup':>8}", flush=True)
    with torch.no_grad(), stage._autocast_ctx(device):
        for Kb in (4, 8, 16):
            xs = [torch.randn(seq, cdim, device=device, dtype=stage.trajectory_dtype) for _ in range(Kb)]
            _bs1_loop(xs[:1])  # warm
            _batched_loop(xs[:2])  # warm
            torch.cuda.synchronize()
            t0 = _time.perf_counter()
            _bs1_loop(xs)
            torch.cuda.synchronize()
            t_bs1 = _time.perf_counter() - t0
            t0 = _time.perf_counter()
            _batched_loop(xs)
            torch.cuda.synchronize()
            t_b = _time.perf_counter() - t0
            print(f"  {Kb:>3} | {t_bs1:>10.3f} | {t_b:>12.3f} | {t_bs1 / t_b:>7.2f}x", flush=True)


if __name__ == "__main__":
    main()
